### PR TITLE
panlint: Add check for features being included from outside their tree

### PR DESCRIPTION
**Pull request by jrha**
i.e. one feature including a template from another

### CODE REVIEW

**Review by ned21 — CHANGES_REQUESTED** [review]
What the goal here? To enforce a rigid hierarchy? That seems a bit too opinionated and is not how we structure our templates, nor can I really think of any good reasons you would want to enforce that.

**Comment by jouvin** [comment]
+1. I fully support @ned21 remark. In the template library we maintain, like the grid ou cloud ones (not to speak of our local templates), we have cases where a feature depends on other features. I don't see any reason to forbid it. If you'd like `panlint` to check for this, I think it should be a `panlint` option, not the default behaviour.

**Comment by jrha** [comment]
Fair enough, I'll make it optional. We enforce a two layer hierarchy at RAL which was originally based on discussions with @gombasg I think, where the only includes that are permitted are:

- From `personality/…` include `feature/…`
- From `feature/…` include `common/…`

**Review by ned21 — CHANGES_REQUESTED** [review]
Can you make this optional and off by default please? We don't require this, and in fact actively encourage contrary behaviour because our feature namespace is a mirror of the namespace used by other artefact repositories. Our general policy is that features should be "complete": therefore if a feature depends on another, you MUST include that feature in your feature, and this would break that.

**Comment by jrha** [comment]
It is.

**Comment by jrha** [comment]
I have amended the commit message to clarify this.

**Review by ned21 — APPROVED** [review]
Apologies, I missed that! `action=store_true` tricked my brain into thinking the default was on.

**Pull request merged**
