### PR TITLE
fixing highlight directive

### PR DESCRIPTION
**Pull request by aka7**
simple fix to documentation fixing highlight directive.

### CODE REVIEW

**Comment by stdweird** [comment]
@aka7 what does this fix?

**Comment by jouvin** [comment]
@stdweird in RST, directives like `highlight` must be introduced by `..`...

**Comment by aka7** [comment]
yes, sorry wasn't clear. it  fixes format of the documentation.  
see top of https://quattor-pan.readthedocs.io/en/stable/pan-book/pan-book.html

**Comment by jouvin** [comment]
Thanks for spotting it.

**Pull request merged**
