### PR TITLE
Fixes utf-8 error

### LINKED ISSUE #102: utf8 error while running tests
from jenkins jobs (not sure if this causes the tests to fail)
```
...
[INFO] Compiling 159 source files to /var/lib/jenkins/workspace/panc/panc/target/test-classes
[ERROR] /var/lib/jenkins/workspace/panc/panc/src/test/java/org/quattor/pan/dml/functions/IpToLongTest.java:[2,36] unmappable character for encoding UTF-8
[ERROR] /var/lib/jenkins/workspace/panc/panc/src/test/java/org/quattor/pan/dml/functions/IpToLongTest.java:[2,43] unmappable character for encoding UTF-8
[INFO] /var/lib/jenkins/workspace/panc/panc/src/test/java/org/quattor/pan/dml/operators/SimpleListVariableTest.java: Some input files use or override a deprecated API.
...
```

### PR DESCRIPTION
**Pull request by iliclaey**
Fixes #102

### CODE REVIEW

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
test this please

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
tests fail with obsucre error, but jenkins log file has
```
INFO: [xUnit] - [JUnit] - 151 test report file(s) were found with the pattern '*/target/surefire-reports/*xml' relative to '/var/lib/jenkins/workspace
/panc-pr-builder' for the testing framework 'JUnit'.
At line 2 of file:/var/lib/jenkins/workspace/panc-pr-builder/panc/target/surefire-reports/TEST-org.quattor.ant.DebugPatternsTest.xml:
SchemaLocation: schemaLocation value = 'https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd' must have even number of
 URI's.
At line 2 of file:/var/lib/jenkins/workspace/panc-pr-builder/panc/target/surefire-reports/TEST-org.quattor.ant.DebugPatternsTest.xml:SchemaLocation: s
chemaLocation value = 'https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd' must have even number of URI's.
Jul 07, 2016 10:17:57 AM org.jenkinsci.plugins.xunit.service.XUnitService warningSystemLogger
WARNING: [xUnit] - The file '/var/lib/jenkins/workspace/panc-pr-builder/panc/target/surefire-reports/TEST-org.quattor.ant.DebugPatternsTest.xml' is an
 invalid file.
Jul 07, 2016 10:17:57 AM org.jenkinsci.plugins.xunit.service.XUnitService errorSystemLogger
SEVERE: [xUnit] - The result file '/var/lib/jenkins/workspace/panc-pr-builder/panc/target/surefire-reports/TEST-org.quattor.ant.DebugPatternsTest.xml'
 for the metric 'JUnit' is not valid. The result file has been skipped.
```
maybe run 
```
mvn versions:display-plugin-updates
```
and update any (other) plugins?

**Comment by stdweird** [comment]
more info, https://issues.jenkins-ci.org/browse/JENKINS-31553, they point to a sure fire plugin fix

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jouvin @jrha who merges pan PRs? esp this easy one so we can have jenkins PR tests (master will still be broken unless we also remove junit reports on the master test)

**Comment by jrha** [comment]
So what fixes the error? The diff is not helpful in explaining what changed!

**Comment by stdweird** [comment]
exactly, some utf-whatever crap. (apparently eclipse displays one of the chracters as a `?` :smile: )

**Pull request merged**
