### PR TITLE
Fix panlint for python 3

### PR DESCRIPTION
**Pull request by wpoely86**
As Fedora 31 lets python point to python 3, it broke panlint. This PR makes sure that panlint works with both python 2 and 3.

### CODE REVIEW

**Comment by wpoely86** [comment]
@stdweird `jenkins0.ugent.be` is not happy but I can't see why.

**Comment by stdweird** [comment]
@wpoely86 looks like shinx issue:
probably harmless
```
/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/source/pan-book/pan-book.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/source/pan-book/pan-book.rst:79: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/source/pan-book/pan-book.rst:1775: ERROR: Unexpected indentation.
/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/source/pan-book/pan-book.rst:1774: WARNING: Inline literal start-string without end-string.
/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/source/running/running.rst:139: ERROR: Malformed table.
```
less harmless
```
Exception occurred:
  File "/var/lib/jenkins/.m2/repository/org/python/jython-standalone/2.5.2/jython-standalone-2.5.2.jar/Lib/os.py", line 158, in makedirs
    mkdir(name, mode)
OSError: [Errno 20000] Unknown error: 20000: '/var/lib/jenkins/jobs/panc-pr-builder/workspace/panc-docs/target/docs/html/commands'
The full traceback has been saved in /tmp/sphinx-err-_rwn4R.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
Either send bugs to the mailing list at <http://groups.google.com/group/sphinx-dev/>,
or report them in the tracker at <http://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

**Comment by wpoely86** [comment]
@stdweird could you show what is being tested/run by Jenkins? I rather put it in a Jenkinsfile so I can at least see what is happening.

**Comment by wpoely86** [comment]
I've added the full tests to the travis config. They pass on my laptop and on Travis.

The error seems more related to the used jython version: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=752357

**Comment by ned21** [comment]
Is 906995d also pep8? Could it be squashed into 57a9b5d to make the history easier to traverse?

What's the rationale for 5cccb4b? Not against it but adding dependencies comes with a trade-off.

945ee05 could do with some explanation. I guess it's because the recent changes make it work on both 2 and 3? Is there an automated test to make sure that the code remains cross-compatible?

1446635 - could you be more specific about what is being "fixed" and why?

**Comment by wpoely86** [comment]
@ned21 I've changed the commit history based on your remarks.

The `six` dependency is needed to have both python2 and python3 compatibility. Once we go python3 only, it can be dropped. It's a very common dependency so it should not give any issues.

945ee05 (changing the shebang) was a mistake. It should not have changed at all.

**Comment by wpoely86** [comment]
I would just use Travis. Those logs are easy to read for everybody and it should be easy to reproduce what it does. And it's clear what exactly is being tested.

**Comment by ned21** [comment]
@wpoely86 Looks like the Jenkins build is an organisation wide notification so can't be disabled for just this repo so I assume it will have to come back at some point, or we can go ahead and merge it.

**Comment by ned21** [comment]
@wpoely86 Please rebase?

**Comment by wpoely86** [comment]
@ned21 done!

**Pull request merged**
