### PR TITLE
panlint: Don't lint blank lines

### LINKED ISSUE #224: panlint: wrong message when template declaration is not on first line
we ran into this:
```
cfg/os/c7x-x86_64/config/core/boot.pan:5: Missing space before and after operator
unique template config/core/boot;
                     ^^^  ^^^
```
when there was documentation above the declaration like:
```
@{
 comments
}

unique template config/core/boot;
```

although it is fine panlint nags about this, it should probably say the declaration needs to be on the first line instead of parsing the line.

### LINKED ISSUE #230: panlint: Blank lines should be ignored (regression)
Root cause of #224

As demonstrated by the debug output, blank lines are no longer being ignored during linting, which causes strange behaviours with the first line rule.

# Example:

## Previous behaviour
```
DEBUG: 0001 Ignored      |# ${license-info}
DEBUG: 0002 Ignored      |# ${developer-info}
DEBUG: 0003 Ignored      |# ${author-info}
DEBUG: 0004 Ignored      |
DEBUG: 0005 ...          |declaration template components/openstack/catalog;
DEBUG: 0006 Ignored      |
DEBUG: 0007 ...          |include 'components/openstack/catalog/murano';
DEBUG: ^^^^ String Range |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG: 0008 Ignored      |
DEBUG: 0009 ...          |@documentation {
DEBUG: 0010 ...          |Type to define OpenStack catalog services
DEBUG: 0011 ...          |}
DEBUG: 0012 ...          |type openstack_catalog_config = {
DEBUG: 0013 ...          |    'murano' ? openstack_murano_config
DEBUG: ^^^^ String Range |    ^^^^^^^^
DEBUG: ^^^^ Path String  |    ^^^^^^^^
DEBUG: 0014 ...          |} with openstack_oneof(SELF, 'murano');
DEBUG: ^^^^ String Range |                             ^^^^^^^^
```

## Current behaviour
```
DEBUG: 0001 Ignored      |# ${license-info}
DEBUG: 0002 Ignored      |# ${developer-info}
DEBUG: 0003 Ignored      |# ${author-info}
DEBUG: 0004 ...          |
DEBUG: 0005 ...          |declaration template components/openstack/catalog;
DEBUG: ^^^^ WS Operator  |                              ^^^
DEBUG: ^^^^ WS Operator  |                                        ^^^
DEBUG: 0006 ...          |
DEBUG: 0007 ...          |include 'components/openstack/catalog/murano';
DEBUG: ^^^^ String Range |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
DEBUG: 0008 ...          |
DEBUG: 0009 ...          |@documentation {
DEBUG: 0010 ...          |Type to define OpenStack catalog services
DEBUG: 0011 ...          |}
DEBUG: 0012 ...          |type openstack_catalog_config = {
DEBUG: 0013 ...          |    'murano' ? openstack_murano_config
DEBUG: ^^^^ String Range |    ^^^^^^^^
DEBUG: ^^^^ Path String  |    ^^^^^^^^
DEBUG: 0014 ...          |} with openstack_oneof(SELF, 'murano');
DEBUG: ^^^^ String Range |                             ^^^^^^^^
```

### PR DESCRIPTION
**Pull request by jrha**
This fixes a regression introduced when lines became objects and the references in this line were not updated correctly.

Fixes #230 and I believe it therefore fixes #224.

### CODE REVIEW

**Comment by wpoely86** [comment]
can we have a test for this?

**Comment by jrha** [comment]
Yep!

**Comment by jrha** [comment]
Can't see Jenkins results, so not sure why it is failing.

**Comment by wpoely86** [comment]
Travis is happy with it, so it should be fine.

**Pull request merged**
