### PR TITLE
panc: TermFactory: cache Term create

### PR DESCRIPTION
**Pull request by stdweird**
Replaces `checkStringIndex` caching from PR #171

### CODE REVIEW

**Comment by jrha** [comment]
Code looks good. Have you accidentally introduced mixed tab/space indentation with this change?

**Comment by stdweird** [comment]
looks that way. probably in all the PRs... feel free to add `?ts=4` to the `.../files` url

**Comment by jrha** [comment]
@stdweird looks like this conflicts with the now merged #170.

**Comment by stdweird** [comment]
@jrha conflict resolved

**Pull request merged**
