### PR TITLE
panlint: allow whitespace around annotation name

### PR DESCRIPTION
**Pull request by stdweird**

### CODE REVIEW

**Comment by jrha** [comment]
Is this really desirable? There is no example of this in the compiler documentation.

**Comment by stdweird** [comment]
it is valid pan code (it even allows for multiple newlines etc etc), as usual the code is the documentation: https://github.com/quattor/pan/blob/master/panc/src/main/jjtree/PanParser.jjt#L179
i also wouldn't encourage to use it, but i'm not sure what panlints role was again: check valid code, or force coding standard...
i'm just pointingthis out, i'm ok with not allowing it

**Comment by jrha** [comment]
The whole point of linting is to encourage good practice, it's the compiler's job to check syntax, I would lean towards not supporting it unless anyone can convince me it's a good idea.

**Comment by jrha** [comment]
I eventually changed my mind, see #262.

**Pull request closed without merging**
