### PR TITLE
panc: only allow digit-only string as candidate list index (and allow anything else as dict key)

### LINKED ISSUE #156: dict keys should be able to start with digit, as long as they aren't digit-only
Why is https://github.com/quattor/pan/blob/master/panc/src/main/java/org/quattor/pan/utils/TermFactory.java#L51 the index pattern, when there's also https://github.com/quattor/pan/blob/master/panc/src/main/java/org/quattor/pan/utils/TermFactory.java#L116

This makes no sense imho

### PR DESCRIPTION
**Pull request by stdweird**
Fixes #156
This is backwards incompatible because eg hex and/or octal notations cannot be used anymore.

### CODE REVIEW

**Comment by stdweird** [comment]
We can introduce hex if it is really used, and/or also get rid of octal support (which is confusing imho)

**Comment by gombasg** [comment]
I don't care much about octal/hex notion (I don't remember ever using it), but I have a feeling that relaxing the rules for dict keys would break XML output. The original rules came from the requirements for XML element and attribute names. Automatic escaping would be possible, but that would require changes to the CCM library, and would open the can of worms about how to detect if something is escaped.

**Comment by stdweird** [comment]
@gombasg can you give an example of what would render invalid xml? 

we should have another discussion at the next workshop on escaping. i tought we could get rid of it altogether (some encoding/decoding might be required; but not the escaping we have now).
@piojo had some idea about this

**Comment by jouvin** [comment]
About the escaping discussion, see very old issues: #17, #32, #35

**Comment by ned21** [comment]
Discussion at RAL workshop: OK in principle. @stdweird will additionally drop octal/hex. Then it just needs to be code reviewed & can be merged.

Once merged and released then Aquilon can be updated to address: https://github.com/quattor/aquilon/issues/54

**Comment by stdweird** [comment]
@jrha @ned21 @jouvin @gombasg after dropping octal mode, what to do with leading `0`?
eg `/a/09` is same path as `/a/9`? or is `09` a syntax error?

**Comment by jrha** [comment]
We're removing support for octal, so my vote would be for it to be syntax error rather than silently accepting the value with a different meaning to previous compiler versions.

**Comment by stdweird** [comment]
@jrha we do that for hex. it is now seen as a key in a dict. btw we can do that also for octals: digits with leading `0` can be used as keys in a dict, so `/adict/042` would be ok.
@ned21 would that help with your issue in aquilon? would have to rename the room (or what was it again) to `042`.

**Comment by ned21** [comment]
@stdweird There is no existing problem with aquilon, it only accepts what the PAN compilers accepts. The specific request is for Aquilon to support rooms named `206-1-001`.

**Comment by stdweird** [comment]
@ned21 ok. but what is your opinion on the octal numbers: syntax error or valid dict key?

**Comment by ned21** [comment]
Leading zeros are ambiguous (is 09 == 9?) so I agree with @jrha we should make them a syntax error.

**Comment by stdweird** [comment]
@ned21 @jrha i removed octal support. this is blocking #170 and #171

**Pull request merged**
