### PR TITLE
Update maven plugins and disable doclint

### LINKED ISSUE #148: Cannot release with Java 1.8
Unfortunately codebase now requires Java 1.8.

Related to quattor/maven-tools#159

### PR DESCRIPTION
**Pull request by jrha**
I disappeared down this rabbit hole trying to fix #148.

### CODE REVIEW

**Comment by jrha** [comment]
Tests now fail as the plugins now require maven 3.3.3 or later, which does not seem to be available on Jenkins.

**Comment by jouvin** [comment]
We should try to fix the doclint problem at some point...

**Comment by jrha** [comment]
We can't, see the maven plugin discussion.

**Comment by stdweird** [comment]
retest this please

**Comment by stdweird** [comment]
@jrha @jouvin all 🥗

**Comment by jrha** [comment]
Ooh, shiny :green_heart:

**Pull request merged**
