### PR TITLE
Add panlint to rpm

### LINKED ISSUE #133: package panlint with panc in the rpm

### PR DESCRIPTION
**Pull request by wpoely86**
fixes #133

### CODE REVIEW

**Comment by stdweird** [comment]
does the rpm resolve all dependencies? in particular the colorama and prettytable ones?

**Comment by wpoely86** [comment]
No, I haven't found how you can do that.

Also, do we want to pull that in with the general panc rpm? Might be worth splitting off panlint into a independent python package?

**Comment by stdweird** [comment]
well, the very least requirements is that the panlint works. i'm not sure how critical the colorama and prettytable are for the functionality, but if not critical, wrap the imports in try/except and deal with the missing modules in the code.
to add dependencies, have a look at https://github.com/quattor/CCM/blob/master/pom.xml#L278
if the rpms are in epel or main repo, it's ok
if not, we need to add them to the externals repo

**Comment by wpoely86** [comment]
As @jrha mentioned that he's working on `panlint`, I will hold off any refactoring until I see a PR.

`prettytable` can easily be made optional, `colorama` is only used for colors which can also be made optional.

**Comment by wpoely86** [comment]
I've updated this to also include the dependencies of panlint in the pan rpm. It's currently hard set to python2. Maybe we should split it off in a independent rpm with a python2 and python3 flavour?

**Comment by jrha** [comment]
With Python2 reaching EOL on January 1st 2020, we should probably only be targeting Python3.

**Comment by ned21** [comment]
panlint calls `#!/usr/bin/env python` -- do we believe it currently works on py2 and py3? We could continue to make it work on py2 but only ship py3 support in the rpm?

**Comment by wpoely86** [comment]
At this moment it works both under python2 and python3 but I'm all in favour of focusing on python3.

**Comment by ned21** [comment]
@wpoely86  - cool, so what's blocking here? Remove the merge commit from this branch, rebase on master, make it work with py3 and we can merge?

**Comment by jrha** [comment]
@hpcugentbot please test this please

**Comment by jrha** [comment]
I've verified that the Maven tests all pass correctly locally, the RPM is built with the correct dependencies and installs correctly.
Seems like Jenkins is having issues again.

**Pull request merged**
